/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class se_abjorklund_win32_platform_JNIPlatform */

#ifndef _Included_se_abjorklund_win32_platform_JNIPlatform
#define _Included_se_abjorklund_win32_platform_JNIPlatform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_abjorklund_win32_platform_JNIPlatform
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_se_abjorklund_win32_platform_JNIPlatform_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
