/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class se_abjorklund_win32_jna_dsound_DSoundJNI */

#ifndef _Included_se_abjorklund_win32_jna_dsound_DSoundJNI
#define _Included_se_abjorklund_win32_jna_dsound_DSoundJNI
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     se_abjorklund_win32_jna_dsound_DSoundJNI
     * Method:    initDSound
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_se_abjorklund_win32_jna_dsound_DSoundJNI_initDSound
        (JNIEnv *, jobject);
    
    /*
     * Class:     se_abjorklund_win32_jna_dsound_DSoundJNI
     * Method:    startPlayingBuffer
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_se_abjorklund_win32_jna_dsound_DSoundJNI_startPlayingBuffer
        (JNIEnv *, jobject);
    
    /*
     * Class:     se_abjorklund_win32_jna_dsound_DSoundJNI
     * Method:    playSquareWave
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_se_abjorklund_win32_jna_dsound_DSoundJNI_playSquareWave
        (JNIEnv *, jobject);
    
#ifdef __cplusplus
}
#endif
#endif
