/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class se_abjorklund_win32_jna_xaudio2_XAudio2JNI */

#ifndef _Included_se_abjorklund_win32_jna_xaudio2_XAudio2JNI
#define _Included_se_abjorklund_win32_jna_xaudio2_XAudio2JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_abjorklund_win32_jna_xaudio2_XAudio2JNI
 * Method:    initXAudio2
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_se_abjorklund_win32_jna_xaudio2_XAudio2JNI_initXAudio2
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     se_abjorklund_win32_jna_xaudio2_XAudio2JNI
 * Method:    startSource
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_se_abjorklund_win32_jna_xaudio2_XAudio2JNI_startSource
  (JNIEnv *, jobject, jint);

/*
 * Class:     se_abjorklund_win32_jna_xaudio2_XAudio2JNI
 * Method:    stopSource
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_se_abjorklund_win32_jna_xaudio2_XAudio2JNI_stopSource
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
