/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class se_abjorklund_win32_JNIPlatform */

#ifndef _Included_se_abjorklund_win32_JNIPlatform
#define _Included_se_abjorklund_win32_JNIPlatform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_abjorklund_win32_JNIPlatform
 * Method:    start
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_se_abjorklund_win32_JNIPlatform_start
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
